---
# Feature Definition (FD) for the ConfigRuleEBSInstance
# This is a feature that creates AWS Config rule which checks (by default)
#  whether completed instances have the following tags
# "Application, Name, Environment, Owner, Project, Compliance, InstanceName"

# Partition Key = Feature
# No sort key needed

Feature: ConfigRuleEBSInstance
Version: '10.0.0.3'
StandardCreationBatch: 2
EnableFeature: true
FeatureParams:  
  pFtEbsInstInstanceIdListToSkip:
    Type: String
    Default: "Blank"
    Description: "List of instances to be skipped from compliance check.For multiple instances use comma separation."
Standards:
  - Gold
Owner:
  Name: AWS Platform Engineering Team
  Email: awspe-all@dxc.com
  OtherContactInfo: AWS Platform Engineering team, DXC Technology
Purpose: AWS Config rule to verify whether completed instances have mentioned tags
ScopeOverridesAllowed:
  - Global
  - Customer
  - OrganizationUnit
  - Account
  - Region
  - VPC
  - Subnet
  - Instance
  - Volume
AllowDisable: true
ResourceDeployment:
  - EBSInstanceConfig.yaml
DependsOnFeature:
  - ConfigService
