---
# Feature Definition (FD) for the ConfigRuleS3PublicRead
# This is a feature that creates Config rule to prohibit S3 public read

# Partition Key = Feature
# No sort key needed

Feature: ConfigRuleS3PublicRead
Version: '7.0.0.2'
StandardCreationBatch: 2
EnableFeature: true
FeatureParams:
  pwhitelistResources:
    Type: String
    Default: "AWSPE-NOVALUE"
    Description: "S3 bucket names for which no incidents to be created in ServiceNow. seperated by comma, eg:demo1,demo2"
Standards:
  - Gold
Owner:
  Name: AWS Platform Engineering Team
  Email: awspe-all@dxc.com
  OtherContactInfo: AWS Platform Engineering team, DXC Technology
Purpose: AWS Config rule to prohibit s3 public read
ScopeOverridesAllowed:
  - Global
  - Customer
  - OrganizationUnit
  - Account
  - Region
  - VPC
  - Subnet
  - Instance
  - Volume
AllowDisable: true
ResourceDeployment:
  - S3BucketPublicReadProhibited.yaml
DependsOnFeature:
  - ConfigService