---
AWSTemplateFormatVersion: 2010-09-09

Description: DXC Managed Services - Integration of Crowdstrike with Security Hub

Parameters:

  pFeatureVersion:
    Type: String
    Default: 'None'
    Description: "[DO NOT CHANGE] Version of the Feature. To be Filled by creating/parent stack"

  pDXCS3KeyPrefix:
    Type: String
    Default: 'None'
    Description: "[DO NOT CHANGE] S3 path to the Lambda_functions of Feature. To be Filled by creating/parent stack"

  pDXCS3BucketName:
    Type: "AWS::SSM::Parameter::Value<String>" 
    Default: /DXC/SES/Module/AwsInspectorV2/S3AssetBucket
    Description: "[DO NOT CHANGE] SSM Parameter for bucket location"

  pAutoUpdateHash:
    Description: '[Do Not change] Required to Create/Update the Feature automatically on ses-standards-master update'
    Default: '0'
    Type: String    

Resources:

  rEnableAWSInspectorV2LambdaRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        -
          PolicyName: "LambdaExecution"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:

              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:DescribeLogGroups
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:PutRetentionPolicy
                Resource:
                  - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/dxc-awsms-EnableAWSInspectorV2*'
              - Effect: Allow
                Action:
                  - "Inspector2:Enable"
                  - "Inspector2:TagResource"
                  - "iam:CreateServiceLinkedRole"
                  - "dynamodb:GetItem"
                Resource: "*"
      Tags:
      - Key: Application
        Value: !Ref 'AWS::StackName'
      - Key: Name
        Value: "rEnableAWSInspectorV2LambdaRole"
      - Key: Owner
        Value: DXC
      - Key: Purpose
        Value: "EnableInspectorV2"

  rEnableAWSInspectorV2Lambda:
    Type: AWS::Lambda::Function
    Properties:
      Description: "Lambda function which enables aws inspector v2"
      FunctionName: !Join ["-", ["dxc-awsms-EnableAWSInspectorV2", !Ref "AWS::Region"]]
      Code:
        S3Bucket: !Ref pDXCS3BucketName
        S3Key: !Sub "${pDXCS3KeyPrefix}/aws_inspector.zip" 
      Handler: index.lambda_handler
      MemorySize: 128
      Role: !GetAtt rEnableAWSInspectorV2LambdaRole.Arn
      Runtime: python3.11
      Timeout: 60
      Tags:
        - Key: Owner
          Value: DXC
        - Key: Purpose
          Value: "EnableInspectorV2"

  rEnableAWSInspectorV2LambdaCustom:
    Type: 'AWS::CloudFormation::CustomResource'
    Version: '1.0'
    Properties:
      ServiceToken: !GetAtt rEnableAWSInspectorV2Lambda.Arn
      pUpdateHash: !Ref pAutoUpdateHash      