---
# Feature Definition (FD) for AWSPatchingAutomation

# Partition Key = Feature
# No sort key needed

Feature: AwsPatchingAutomation
Version: '12.0.0.8'
StandardCreationBatch: 4
EnableFeature: true
Standards:
  - Gold
Owner: 
  Name: 'AWS Platform Engineering Team'
  Email: awspe-all@dxc.com
  OtherContactInfo: AWS Platform Engineering team, DXC Technology
Purpose: 'Perform the Patching activity on the eligible EC2 Instances.' 
AllowDisable: true
ResourceDeployment:
  - aws_patching_automation.yaml
