---
# Partition Key = Feature
# No sort key needed

Feature: ConfigNotificationService
Version: '9.0.0.5'
StandardCreationBatch: 2
EnableFeature: true
FeatureParams:
  pfSnowInciPriority:
      Type: String
      Default: '3'
      AllowedValues: ['1', '2', '3', '4', '5']
      Description: '[Required] Default is set to 3-Minor, other priorities are 1-critical, 2-major, 3-minor, 4-warning, 5-ok (can be updated if necessary)'
Standards:
  - Gold
Owner:
  Name: AWS Platform Engineering Team
  Email: awspe-all@dxc.com
  OtherContactInfo: AWS Platform Engineering team, DXC Technology
Purpose: Common SNS Topic Notification to SNOW via SNS topic
ScopeOverridesAllowed:
  - Global
  - Customer
  - OrganizationUnit
  - Account
  - Region
  - VPC
  - Subnet
  - Instance
  - Volume
AllowDisable: true
ResourceDeployment:
  - ConfigNotificationSystem.yaml
DependsOnFeature:
  - ConfigService
  - CommonServicenow
