---
# Feature Definition (FD) for CrowdstrikeIntegration

# Partition Key = Feature
# No sort key needed

Feature: CrowdstrikeIntegration
Version: '13.0.0.6'
StandardCreationBatch: 3
EnableFeature: false
Standards:
  - Gold
Owner: 
  Name: AWS Platform Engineering Team
  Email: awspe-all@dxc.com
  OtherContactInfo: AWS Platform Engineering team, DXC Technology
Purpose: Integration of Crowdstrike with SecurityHub

FeatureParams:

  InstanceType:
    Type: String
    Default: "t2.large"
    Description: 'Instance type of the FIG instance.'

  Key:
    Type: String
    Description: 'The key used to access the instance.'
    Default: ''

  VpcName:
    Type: AWS::EC2::VPC::Id
    Description: 'VPC Identifier, Provide any Management VPC V2 ID, default is Mgmt VPC V2 ID.'
    Default: ''

  Subnet:
    Type: String
    Default: ''
    Description: 'Subnet in which FIG instance will be created. They are provided in runtime using custom resource defined in Resources'

  SecurityGroup:
    Type: String
    Default: ''
    Description: '[DO NOT Change] Default SG for the WL VPC will le loaded from SES.'

  RootVolumeSize:
    Type: Number
    Default: 50
    Description: 'Root volume size of the fig instance'

  RootVolumeEncryption:
    Type: String
    Default: false
    Description: 'Root volume encryption for Hardened Ami'

  pSecretManager:
    Type: String
    Default: 'DXC-AWSMS-Offerings-SecretKeys'
    Description: 'Secrets Manager secrets name containing the Falcon Client Id and Client Secret'

  CommonSNSTopic:
    Description: '[DO NOT CHANGE] ssm param of Common SNS Topic for service now alerts'
    Type: "AWS::SSM::Parameter::Value<String>"
    Default: "/dxc/AWSMS/CommonSNSTopicForSnowAndEmail"

  pSSMDocumentName:
    Type: String
    Default: 'FigServerVersionUpgradeSSMDocument'
    Description: 'Name of the SSM Document.'

  pFigServerName:
    Default: 'SecurityHubIntegrationServer'
    Description: Provide EC2 Instance Name where document needs to be executed.
    Type: String

  pFalconSSMFigSeverityThreshold:
    Default: '3'
    Description: Falcon Fig SeverityThreshold value as per configuration in crowdstrike github docs.
    Type: String

  pFalconCloudRegion:
    Default: 'us-2'
    Description: Falcon cloud region. Expected falcon cloud region are - us-1, us-2, eu-1 and us-gov-1
    Type: String
  
  pAWSRegion:
    Default: 'us-west-2'
    Description: Provide the AWS Region where you are working on
    Type: String

  pCrowdStrikeCID:
    Default: ''
    Description: Provide CID value which can be retrieved from SSM Parameter
    Type: String
  
  pUpdateHash:
    Type: String 
    Description: This hash initiates updates to the rSSMDocumentFigExecLambdaFunction lambda in UPDATE event. This parameter MUST be changed to trigger an update.
    Default: 0

AllowDisable: true
ResourceDeployment:
  - CrowdstrikeIntegration.yaml
DependsOnFeature:
  - CommonSNSTopic