---
AWSTemplateFormatVersion: 2010-09-09
Description: "Checks that Amazon S3 buckets do not allow public write access.
  If an Amazon S3 bucket policy or bucket ACL allows public write access,
  the bucket is noncompliant."
Parameters:
  pDXCS3KeyPrefix:
    Type: String
    Default: None
    Description: "[DO NOT CHANGE] S3 path to the Lambda_functions of Feature. To be Filled by creating/parent stack"
  pFeatureVersion:
    Type: String
    Default: 'None'
    Description: "[DO NOT CHANGE] Version of the Feature. To be Filled by creating/parent stack"
Resources:
  rAWSConfigRule:
    Type: 'AWS::Config::ConfigRule'
    Properties:
      Description: "Checks that Amazon S3 buckets do not allow public
        write access. If an Amazon S3 bucket policy or bucket ACL allows
        public write access, the bucket is noncompliant."
      Scope:
        ComplianceResourceTypes:
          - 'AWS::S3::Bucket'
      Source:
        Owner: AWS
        SourceIdentifier: S3_BUCKET_PUBLIC_WRITE_PROHIBITED