---
# Feature Definition (FD) for AWSAthenaMonitoring

# Partition Key = Feature
# No sort key needed

Feature: AWSAthenaMonitoring
Version: '9.0.0.2'
StandardCreationBatch: 3
EnableFeature: false
Standards:
  - Gold
Owner: 
  Name: AWS Platform Engineering Team
  Email: awspe-all@dxc.com
  OtherContactInfo: AWS Platform Engineering team, DXC Technology
Purpose: Creating the cloudwatch alarms for Athena service
FeatureParams:
  pCommonIncidentTopic:
    Description: SSM Param to create the Incidents in Service-Now with priroity fetched from DDB - FtCloudWatchAlarmsIncidentPriorities
    Type: "AWS::SSM::Parameter::Value<String>" 
    Default: /DXC/Alarms/CreateIncident-Default
  pAutoUpdateHash:
    Description: '[Do Not change] Required to Create/Update the Feature automatically on ses-standards-master update'
    Default: '0'
    Type: String
Alarms:
  TotalExecutionTime_SUCCEEDED_Alarm:
    ComparisonOperator: GreaterThanThreshold
    Dimensions:
    - Name: WorkGroup
      Value: <To be Filled>
    - Name: QueryState
      Value: SUCCEEDED
    - Name: QueryType
      Value: DML
    EvaluationPeriods: 3
    MetricName: TotalExecutionTime
    Namespace: AWS/Athena
    Period: 300
    Statistic: Average
    Threshold: 30000
  TotalExecutionTime_FAILED_Alarm:
    ComparisonOperator: GreaterThanThreshold
    Dimensions:
    - Name: WorkGroup
      Value: <To be Filled>
    - Name: QueryState
      Value: FAILED
    - Name: QueryType
      Value: DML
    EvaluationPeriods: 3
    MetricName: TotalExecutionTime
    Namespace: AWS/Athena
    Period: 300
    Statistic: Average
    Threshold: 30000
  TotalExecutionTime_CANCELED_Alarm:
    ComparisonOperator: GreaterThanThreshold
    Dimensions:
    - Name: WorkGroup
      Value: <To be Filled>
    - Name: QueryState
      Value: CANCELED
    - Name: QueryType
      Value: DML
    EvaluationPeriods: 3
    MetricName: TotalExecutionTime
    Namespace: AWS/Athena
    Period: 300
    Statistic: Average
    Threshold: 30000
  ProcessedBytes_FAILED_Alarm:
    ComparisonOperator: GreaterThanThreshold
    Dimensions:
    - Name: WorkGroup
      Value: <To be Filled>
    - Name: QueryState
      Value: FAILED
    - Name: QueryType
      Value: DML
    EvaluationPeriods: 3
    MetricName: ProcessedBytes
    Namespace: AWS/Athena
    Period: 300
    Statistic: SampleCount
    Threshold: 10
  ProcessedBytes_CANCELED_Alarm:
    ComparisonOperator: GreaterThanThreshold
    Dimensions:
    - Name: WorkGroup
      Value: <To be Filled>
    - Name: QueryState
      Value: CANCELED
    - Name: QueryType
      Value: DML
    EvaluationPeriods: 3
    MetricName: ProcessedBytes
    Namespace: AWS/Athena
    Period: 300
    Statistic: SampleCount
    Threshold: 10
AllowDisable: true
ResourceDeployment:
  - aws_athena_monitoring.yaml
DepensOnFeature:
  - AWSCloudWatchAlarmsIncidentPriorities