---
# Feature Definition (FD) for configure_dynatrace_resources
# This feature will create an ActiveGate role and a monitored account role based on Dynatrace provided CloudFormation templates:
#     https://github.com/dynatrace-oss/cloud-snippets/blob/main/aws/role-based-access/role_based_access_AG_account_template.yml
#     https://github.com/dynatrace-oss/cloud-snippets/blob/main/aws/role-based-access/role_based_access_monitored_account_template.yml
# Partition Key = Feature
# No sort key needed

Feature: ConfigureDynatraceResources 
Version: '10.0.0.1'
StandardCreationBatch: 3
EnableFeature: false

FeatureParams:
  ## Parameters for DynamoDB, duplicated in definition file
  pFtDynConTokenId:
    Type: String
    Default: 'MustBeSet'
    Description: 'This is the External ID (token) created in the DynatraceManaged console when configuring AWS in the Cloud and virtualization menu.  Must be set before deploying the feature.'

Standards:
  - Gold
Owner:
  Name: AWS Platform Engineering Team
  Email: awspe-all@dxc.com
  OtherContactInfo: AWS Platform Engineering team, DXC Technology
Purpose: This feature will create an ActiveGate role and a monitored account role based on Dynatrace provided CloudFormation templates
AllowDisable: True

ResourceDeployment:
  - configure_dynatrace_resources.yaml
