---
# Feature Definition (FD) for the ECS Fargate Automated Deployment CICD Pipeline as a feature 

# Partition Key = Feature
# No sort key needed

Feature: DxcEcsFargateAdCicdPipeline
Version: '10.0.0.1'
StandardCreationBatch: 3
EnableFeature: False
FeatureParams:
  pBuildFile:
    Type: String
    Default: 'buildspec.yaml'
    Description: "Buildspec file to run during the pipeline build stage"
  pBuildFilePush:
    Type: String
    Default: 'buildspecpush.yaml'
    Description: "Buildspec file to run during the pipeline push the image to ECR repossitory" 
  pSourceType:
    Description: "Source type which we are using"
    Type: "String"
    Default: 'GITHUB_ENTERPRISE'  
  pGitHubRepository:
    Type: String
    Default: ''
    Description: "Github repository name eg. <user>/<repo> like cloud/DXC-AWSMS-Offerings"
  pGitHubBranch:
    Type: String
    Default: ''
    Description: 'Provide Git branch for executing the pipeline on code push'
  pGithubSourceLocation:
    Type: String
    Default: ''
    Description: 'This is the source location provided under codebuild project. we need to provide full <GITHUB-URL> here'     
  pCodeBuildSourceVersion:
    Type: String
    Default: ''
    Description: 'This is the codebuild source version and we need to provide the branch name here [OPTIONAL]'
  pCodeStarConnectionARN:
    Type: String
    Description: Enter the connection ARN to establish connection between GIT and AWS Codepipeline
    Default: '' 
  pManualApproval:
    AllowedValues:
      - 'Yes'
      - 'No'
    Default: 'Yes'
    Description: Require manual approval before pushing docker images to ECR repositoy, will email Primary Email and (optionally) Secondary Email specified in the Email Notification Settings section
    Type: String
  pEmailPrimary:
    Default: ''
    Description: Primary email to notify for pending manual approvals and pipeline execution notifications
    Type: String
  pEmailSecondary:
    Default: ''
    Description: Secondary email to notify for pending manual approvals and pipeline execution notifications
    Type: String
  pArtifactsS3KeyLocation:
    Default: 'deploy'
    Description: 'S3 key location of the templates'
    Type: String
  pECRRepositoryName:
    Type: String
    Default: ''
    AllowedPattern: "^[a-z0-9-_/.]*$"
    Description: 'Enter the name of the ECR Repository'
  pEncryptionOption:
    Type: String
    Default: Default KMS
    Description: Select the encryption option for the repository
    AllowedValues:
      - Default KMS
      - Customer Managed KMS
  pKmsKeyArn:
    Type: String
    Description: The KMS key ARN to use for encryption (required if EncryptionOption is KMS) 
    Default: ""
  pImageTagMutability:
    Type: String
    Default: 'MUTABLE'
    Description: 'Provided the MUTABLE as tag Immutability (where tag can be overwritten) so that we can have latest tag in every image deployment'  
  pScanonPush:
    Type: String
    AllowedValues:
      - 'true'
      - 'false'
    Default: 'true'
    Description: 'Based on true and false, Enable(true)/Disable(false) this option if you want to scan the image on first push'
  pCrossRegionReplication:
    Description: Enable cross-region replication by choosing true as an option else keep it default to false.
    Type: String
    AllowedValues:
      - 'true'
      - 'false'
    Default: 'false'
  pCrossAccountReplication:
    Description: Enable cross-account replication by choosing true as an option else keep it default to false.
    Type: String
    AllowedValues:
      - 'true'
      - 'false'
    Default: 'false'
  pCrossRegionDestinationRegions:
    Description: Comma-separated list of destination regions for cross-region replication
    Type: String
    Default: ''
  pCrossAccountDestinationRegions:
    Description: Comma-separated list of destination regions for cross-account replication
    Type: String
    Default: ''
  pCrossAccountDestinationAccountIds:
    Description: Comma-separated list of destination account IDs for cross-account replication
    Type: String
    Default: ''  
  pEcsClusterName:
    Default: ''
    Description: 'Provide the ECS Cluster Name here'
    Type: String   
  pEcsContainerName:
    Type: String
    Default: ''  
    Description: 'Provide the ECS Container Name here'
  pEcsServiceName:
    Default: ''
    Description: 'Provide the ECS Service Name here'
    Type: String  
  pEcsImageDefinitionFileName:
    Default: 'imagedefinitions.json'
    Description: 'Provide the ECS Image Definition file Name here'
    Type: String    

  pPushImageApplyFailedBuildsAlarm:
    Description: 'Enable for creating Failed Builds Alarm for push image project. Pre-Requisite FeatureAWSCloudWatchAlarmsIncidentPriorities is deployed.'
    Type: String
    AllowedValues: ['true', 'false']
    Default: 'true'
  pPushImageFailedBuildsPeriod:
    Description: 'The period, in seconds, over which the statistic is applied. This is required for an alarm based on a metric. Valid values are 10, 30, 60, and any multiple of 60.'
    Type: Number
    Default: 60
  pPushImageFailedBuildsStatistic:
    Description: 'The statistic for the metric associated with the alarm'
    Type: String
    AllowedValues: ['Average','Maximum', 'Minimum', 'SampleCount', 'Sum']
    Default: 'Sum'
  pPushImageFailedBuildsThreshold:
    Description: 'The value to compare with the specified statistic.'
    Type: Number
    Default: 0
    
  pPushImageFailedBuildsEvaluationPeriods:
    Description: 'The number of periods over which data is compared to the specified threshold.'
    Type: Number
    Default: 2
  pPushImageFailedBuildsComparisonOperator:
    Description: 'The arithmetic operation to use when comparing the specified statistic and threshold. The specified statistic value is used as the first operand.'
    Type: String
    Default: 'GreaterThanThreshold'
    AllowedValues: [GreaterThanOrEqualToThreshold','GreaterThanThreshold','GreaterThanUpperThreshold','LessThanLowerOrGreaterThanUpperThreshold','LessThanLowerThreshold','LessThanOrEqualToThreshold', 'LessThanThreshold']

  pBuildAndTagApplyFailedBuildsAlarm:
    Description: 'Enable for creating Failed Builds Alarm for tag and build project. Pre-Requisite FeatureAWSCloudWatchAlarmsIncidentPriorities is deployed.'
    Type: String
    AllowedValues: ['true', 'false']
    Default: 'true'
  pBuildAndTagFailedBuildsPeriod:
    Description: 'The period, in seconds, over which the statistic is applied. This is required for an alarm based on a metric. Valid values are 10, 30, 60, and any multiple of 60.'
    Type: Number
    Default: 60
  pBuildAndTagFailedBuildsStatistic:
    Description: 'The statistic for the metric associated with the alarm'
    Type: String
    AllowedValues: ['Average','Maximum', 'Minimum', 'SampleCount', 'Sum']
    Default: 'Sum'
  pBuildAndTagFailedBuildsThreshold:
    Description: 'The value to compare with the specified statistic.'
    Type: Number
    Default: 0
    
  pBuildAndTagFailedBuildsEvaluationPeriods:
    Description: 'The number of periods over which data is compared to the specified threshold.'
    Type: Number
    Default: 2
  pBuildAndTagFailedBuildsComparisonOperator:
    Description: 'The arithmetic operation to use when comparing the specified statistic and threshold. The specified statistic value is used as the first operand.'
    Type: String
    Default: 'GreaterThanThreshold'
    AllowedValues: [GreaterThanOrEqualToThreshold','GreaterThanThreshold','GreaterThanUpperThreshold','LessThanLowerOrGreaterThanUpperThreshold','LessThanLowerThreshold','LessThanOrEqualToThreshold', 'LessThanThreshold']

  pPriorityIncidentTopic:
    Description: SSM Param to create the Incidents in Service-Now with priority fetched from DDB - FtCloudWatchAlarmsIncidentPriorities
    Type: "AWS::SSM::Parameter::Value<String>" 
    Default: /DXC/Alarms/CreateIncident-Default

Standards:
  - Gold
Owner:
  Name: AWS Platform Engineering Team
  Email: awspe-all@dxc.com
  OtherContactInfo: AWS Platform Engineering team, DXC Technology
Purpose: CICD Pipeline to push the docker images on ECR repository and then does the automated deployment on ECS Containerized Infrastructure whenever there is an modification in the code on the GITHUB Repo branches.
AllowDisable: true
ResourceDeployment:
  - DxcEcsFargateAdCicdPipeline.yaml
DependsOnFeature:
  - AWSCloudWatchAlarmsIncidentPriorities