AWSTemplateFormatVersion: 2010-09-09
Description: 'A regional template which creates a CloudWatch Anomaly detection lambda functions'
Parameters:
  pDXCS3BucketName:
    Type: "AWS::SSM::Parameter::Value<String>" 
    Default: /DXC/SES/Module/CWStepfunctionAnomalyDetection/S3AssetBucket
    Description: SSM Parameter for bucket location
  pDXCS3KeyPrefix:
    Type: String
    Default: 'none'
    Description: "[DO NOT CHANGE] S3 path to the Lambda_functions of Feature. To be Filled by creating/parent stack"
  pFeatureVersion:
    Type: String
    Default: 'None'
    Description: "[DO NOT CHANGE] Version of the Feature. To be Filled by creating/parent stack"
  pSNSTopicParam:
    Type: "AWS::SSM::Parameter::Value<String>" 
    Default: /DXC/Instance/AlarmTopic
    Description: SSM Parameter for SNS Topic

Resources:

  rDxcmsADEC2DynamoDBTable: 
    Type: AWS::DynamoDB::Table
    Properties: 
      BillingMode: 'PAY_PER_REQUEST'
      AttributeDefinitions: 
        - 
          AttributeName: "Metric Name"
          AttributeType: "S"
      KeySchema: 
        - 
          AttributeName: "Metric Name"
          KeyType: "HASH"
      TableName: "Ft_Dxcms_Anomalydetection_StepFunction"
      Tags:
      - Key: Application
        Value: !Ref 'AWS::StackName'
      - Key: Name
        Value: rDxcmsAnomalyDetectionDynamoDbTable
      - Key: Owner
        Value: DXC

  rDxcmsCWStepFunctionLambdaExecutionRole:
    Type: 'AWS::IAM::Role'
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      RoleName:  !Sub 'dxcms-cw-stepfunction-lambda-exec-role-${AWS::Region}'
      Tags:
      - Key: Application
        Value: !Ref 'AWS::StackName'
      - Key: Name
        Value: rDxcmsCWAnomalyDetectionLambdaRole
      - Key: Owner
        Value: DXC
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: 'sts:AssumeRole'
      Path: "/"
      Policies:
        - PolicyName: !Sub "Dxcms-cw-stepfunction-lambda_${AWS::Region}"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:

              - Sid: 'DynamoDBAccessPermisson'
                Effect: Allow
                Action:
                - dynamodb:Scan
                - dynamodb:PutItem
                - dynamodb:GetItem
                Resource: 
                - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/Ft_Dxcms_Anomalydetection_StepFunction/stream/*"
                - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/Ft_Dxcms_Anomalydetection_StepFunction/index/*"
                - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/Ft_Dxcms_Anomalydetection_StepFunction"                                    

              - Sid: lambdaAccessPermission
                Effect: Allow
                Action:
                  - 'lambda:InvokeFunction'
                Resource: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:dxcms_cw_*'

              - Sid: S3AccessPermission
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:ListBucket
                Resource: 
                - !Sub 'arn:aws:s3:::dxc.customer.config-${AWS::AccountId}-${AWS::Region}/*'
                - !Sub 'arn:aws:s3:::cloudops-anomaly-detection-reports/*'
                Effect: Allow 

              - Sid: CWAccessPermission
                Action:
                  - "cloudwatch:DescribeAlarmsForMetric"
                  - "cloudwatch:DisableAlarmActions"
                  - "cloudwatch:PutMetricAlarm"
                  - "cloudwatch:EnableAlarmActions"
                Resource: "*"
                Effect: Allow 

              - Sid: StateMachinePermisssions
                Action:
                - states:ListExecutions
                - states:ListStateMachines
                - states:ListTagsForResource
                Effect: Allow
                Resource: "*"

  rDxcmsCWCreateStepFunctionAnomalyAlarmLA:
    Type: 'AWS::Lambda::Function'
    Properties:
      Handler: create_ad_stepfunction_alarm.lambda_handler
      Role: !GetAtt
        - rDxcmsCWStepFunctionLambdaExecutionRole
        - Arn
      Environment:
        Variables:
          table_name: "Ft_Dxcms_Anomalydetection_StepFunction"
      Description: 'Lambda to create the anomaly alarm and disable the static alarm'
      Code:
        S3Bucket: !Ref pDXCS3BucketName
        S3Key:  !Sub '${pDXCS3KeyPrefix}/create_ad_stepfunction_alarm.zip'
      Runtime: python3.11
      FunctionName: !Sub "dxcms-cw-create-ad-stepfunction-alarm-${AWS::Region}"
      Timeout: 900
      Tags:
      - Key: Application
        Value: !Ref 'AWS::StackName'
      - Key: Name
        Value: !Sub "dxcms-cw-create-anomaly-detection-stepfunction-alarm-${AWS::Region}"
      - Key: Owner
        Value: DXC

  rDxcmsCWStepFunctionDynamodDBLambdaLA:
    Type: 'AWS::Lambda::Function'
    Properties:
      Handler: load_dynamodb_stepfunction.lambda_handler
      Role: !GetAtt 
        - rDxcmsCWStepFunctionLambdaExecutionRole
        - Arn
      Environment:
        Variables:
          table_name: "Ft_Dxcms_Anomalydetection_StepFunction"
          sns_topic_arn: !Ref pSNSTopicParam
      Description: 'Lambda to load the data into dynamodb'
      Code:
        S3Bucket: !Ref pDXCS3BucketName
        S3Key:  !Sub '${pDXCS3KeyPrefix}/load_dynamodb_stepfunction.zip'
      Runtime: python3.11
      FunctionName: !Sub "dxcms-cw-load-dynamodb-stepfunction-alarm-${AWS::Region}"
      Timeout: 900
      Tags:
      - Key: Application
        Value: !Ref 'AWS::StackName'
      - Key: Name
        Value: !Sub "dxcms-cw-load-dynamodb-stepfunction-alarm-${AWS::Region}"
      - Key: Owner
        Value: DXC

  customInvokeLoaddynamodbtepFunctionLambda:
    Type: Custom::AwsLambdaLoadDynamodb
    DependsOn: rDxcmsCWStepFunctionDynamodDBLambdaLA
    Properties:
        ServiceToken: !GetAtt rDxcmsCWStepFunctionDynamodDBLambdaLA.Arn

  