---
AWSTemplateFormatVersion: '2010-09-09'
Description: "CF Template to create AWS Config rule which checks
  whether running instances are using specified AMIs tagged
  accordingly. Compliant AMIs are tagged with either
  Environment:Production, Environment:Staging, or Environment:QA.
  If additional debuggingis required, there is a TracingFlag
  parameter that can be set to enable AWS X-Ray tracing."

Parameters:
  pFeatureVersion:
    Type: String
    Default: 'None'
    Description: "[DO NOT CHANGE] Version of the Feature. To be Filled by creating/parent stack"
  
  pDXCS3KeyPrefix:
    Type: String
    Default: 'None'
    Description: "[DO NOT CHANGE] S3 path to the Lambda_functions of Feature. To be Filled by creating/parent stack"
  
  TracingFlag:
    Description: "Flag to enable AWS X-Ray tracing (set to Active)
      for debugging. Default setting is PassThrough."
    Type: "AWS::SSM::Parameter::Value<String>"
    Default: "/DXC/CloudWatch/TracingFlag"

  DXCS3BucketName:
    Type: "AWS::SSM::Parameter::Value<String>" 
    Default: /DXC/SES/Module/ConfigRuleApprovedAmis/S3AssetBucket
    Description: "[DO NOT CHANGE] SSM Parameter for bucket location"

  pApprovedAMIsTags:
    Description: "List of tag-key:tag-value which are used to
      evaluate whether or not an AMI is compliant"
    Type: CommaDelimitedList
    Default: "Environment:Production,Environment:Staging,Environment:QA"
  
  pFtApprAmiAmiListToSkip:
    Type: String
    Default: "Blank"
    Description: "List of Amis to be skipped from config compliance check. For multiple Amis to be skipped evaluating against the config rule, use comma separated values."

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "Location of DXC Managed Services Assets:"
        Parameters:
          - DXCS3BucketName
    ParameterLabels:
      DXCS3BucketName:
        default: "S3 Bucket Name:"

Resources:
  LambdaExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        -
          PolicyName: "LambdaExecution"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Action:
                  - ec2:DescribeTags
                  - ec2:DescribeImages
                  - ec2:DescribeImageAttribute
                  - ec2:DescribeRegions
                Effect: Allow
                Resource: "*"
              - Effect: Allow
                Action:
                  - logs:*
                Resource: "arn:aws:logs:*:*:*"
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource: "arn:aws:s3:::*"
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource: "arn:aws:s3:::*/AWSLogs/*/Config/*"
              - Effect: Allow
                Action:
                  - "config:Put*"
                  - "config:Get*"
                  - "config:List*"
                  - "config:Describe*"
                Resource: "*"
              - Effect: Allow
                Action:
                  - xray:PutTraceSegments
                  - xray:PutTelemetryRecords
                Resource: "*"
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                Resource: "*"                     
  ConfigPermissionToCallLambda:
    Type: "AWS::Lambda::Permission"
    Properties:
      FunctionName:
        Fn::GetAtt:
          - ApprovedAMIsComplianceCheck
          - Arn
      Action: "lambda:InvokeFunction"
      Principal: "config.amazonaws.com"
  ApprovedAMIsComplianceCheck:
    Type: "AWS::Lambda::Function"
    Properties:
      Description: "Lambda function that evaluates if instances
        were launched by approved AMIs based on specific tags"
      Code:
        S3Bucket: !Ref DXCS3BucketName
        S3Key: !Sub "${pDXCS3KeyPrefix}/approved_amis.zip"
      Handler: "approved_amis.lambda_handler"
      Runtime: python3.11
      Timeout: 60
      TracingConfig:
        Mode: !Ref TracingFlag
      Role:
        Fn::GetAtt:
          - LambdaExecutionRole
          - Arn
      Tags:
        -
          Key: Purpose
          Value: "Custom Lambda for AWS Config Rule - approved-amis-by-tag"
  AWSConfigRule:
    Type: "AWS::Config::ConfigRule"
    Properties:
      Description: "Checks whether running instances are using
        approved AMIs by specific tags -
        Environment:QA, Environment:Production, or Environment:Staging."
      InputParameters:
        amisByTagKeyAndValue: !Ref pApprovedAMIsTags
      Scope:
        ComplianceResourceTypes:
          - AWS::EC2::Instance
      Source:
        Owner: "CUSTOM_LAMBDA"
        SourceDetails:
          -
            EventSource: "aws.config"
            MessageType: "ConfigurationItemChangeNotification"
        SourceIdentifier:
          Fn::GetAtt:
            - ApprovedAMIsComplianceCheck
            - Arn
    DependsOn: ConfigPermissionToCallLambda
