---
# Feature Definition (FD) for AWSCognitoMonitoring

# Partition Key = Feature
# No sort key needed

Feature: AWSCognitoMonitoring
Version: '9.0.0.2'
StandardCreationBatch: 3
EnableFeature: false
Standards:
  - Gold
Owner: 
  Name: AWS Platform Engineering Team
  Email: awspe-all@dxc.com
  OtherContactInfo: AWS Platform Engineering team, DXC Technology
Purpose: Creating the cloudwatch alarms for Cognito service
FeatureParams:
  pCommonIncidentTopic:
    Description: SSM Param to create the Incidents in Service-Now with priroity fetched from DDB - FtCloudWatchAlarmsIncidentPriorities
    Type: "AWS::SSM::Parameter::Value<String>" 
    Default: /DXC/Alarms/CreateIncident-Default
  pAutoUpdateHash:
    Description: '[Do Not change] Required to Create/Update the Feature automatically on ses-standards-master update'
    Default: '0'
    Type: String
Alarms:
  SignUpThrottles_Alarm:
    ComparisonOperator: GreaterThanThreshold
    Dimensions:
    - Name: UserPool
      Value: <TO BE FILLED>
    - Name: UserPoolClient
      Value: <TO BE FILLED>
    EvaluationPeriods: 3
    MetricName: SignUpThrottles
    Namespace: AWS/Cognito
    Period: 300
    Statistic: Sum
    Threshold: 10
  SignInThrottles_Alarm:
    ComparisonOperator: GreaterThanThreshold
    Dimensions:
    - Name: UserPool
      Value: <TO BE FILLED>
    - Name: UserPoolClient
      Value: <TO BE FILLED>
    EvaluationPeriods: 3
    MetricName: SignInThrottles
    Namespace: AWS/Cognito
    Period: 300
    Statistic: Sum
    Threshold: 10
  FederationThrottles_Alarm:
    ComparisonOperator: GreaterThanThreshold
    Dimensions:
    - Name: UserPool
      Value: <TO BE FILLED>
    - Name: UserPoolClient
      Value: <TO BE FILLED>
    - Name: IdentityProvider
      Value: <TO BE FILLED>
    EvaluationPeriods: 3
    MetricName: FederationThrottles
    Namespace: AWS/Cognito
    Period: 300
    Statistic: Sum
    Threshold: 10
AllowDisable: true
ResourceDeployment:
  - aws_cognito_monitoring.yaml
DepensOnFeature:
  - AWSCloudWatchAlarmsIncidentPriorities