---
# Feature Definition (FD) for the Common Servicenow feature
# Single solution to process alarm and event inputs from all offering lambdas and services and create ServiceNow incident with proper priority using Agnostic API

# Partition Key = Feature
# No sort key needed

Feature: CommonServicenow
FeatureParams:
  pNotifyEmail:
    Description: AWS SSM Parameter that contains the notification email address
      for DLQ and Parser Queue message buildup
      (you will receive an email, reply to confirm the subscription)
    Type: "AWS::SSM::Parameter::Value<String>"
    Default: "/DXC/Notification/DXCNotifyEmail"
  pParserQDelay:
    Description: 'The time in seconds for which the delivery of all messages in the queue is delayed. You can specify an integer value of 0 to 900'
    Type: Number
    Default: 0
  pParserQVisTimeout:
    Description: 'The length of time during which a message will be unavailable after a message is delivered from the queue. This blocks other components from receiving the same message'
    Type: Number
    Default: 240
  pParserQMaxRecCnt:
    Description: 'The number of times a message is delivered to the source queue before being moved to the dead-letter queue'
    Type: Number
    Default: 5
  pComSnowDlqDelay:
    Description: 'The time in seconds for which the delivery of all messages in the queue is delayed. You can specify an integer value of 0 to 900'
    Type: Number
    Default: 0
  pComSnowDlqVisTimeout:
    Description: 'The length of time during which a message will be unavailable after a message is delivered from the queue. This blocks other components from receiving the same message'
    Type: Number
    Default: 300
  pParserQAlarmThrshld:
    Description: 'Timeframe that a message can remain in the Parser Queue before an e-mail notification is sent indicating a buildup of messages in the queue'
    Type: Number
    Default: 300
  pParserQAlarmPeriod:
    Description: 'The period, in seconds, over which the statistic is applied'
    Type: Number
    Default: 60
  pParserQAlarmEvalPeriod:
    Description: 'The number of periods over which data is compared to the specified threshold'
    Type: Number
    Default: 1
  pDlqAgeAlarm1Thrshld:
    Description: 'Timeframe that a message can remain in the Parser Queue before an e-mail notification is sent indicating a buildup of messages in the queue'
    Type: Number
    Default: 3600
  pDlqAgeAlarm1Period:
    Description: 'The period, in seconds, over which the statistic is applied'
    Type: Number
    Default: 600
  pDlqAgeAlarm1EvalPeriod:
    Description: 'The number of periods over which data is compared to the specified threshold'
    Type: Number
    Default: 1
  pDlqAgeAlarm2Thrshld:
    Description: 'Timeframe that a message can remain in the Parser Queue before an e-mail notification is sent indicating a buildup of messages in the queue'
    Type: Number
    Default: 14000
  pDlqAgeAlarm2Period:
    Description: 'The period, in seconds, over which the statistic is applied'
    Type: Number
    Default: 600
  pDlqAgeAlarm2EvalPeriod:
    Description: 'The number of periods over which data is compared to the specified threshold'
    Type: Number
    Default: 1
  pDlqCntAlarm1Thrshld:
    Description: 'Timeframe that a message can remain in the Parser Queue before an e-mail notification is sent indicating a buildup of messages in the queue'
    Type: Number
    Default: 1
  pDlqCntAlarm1Period:
    Description: 'The period, in seconds, over which the statistic is applied'
    Type: Number
    Default: 60
  pDlqCntAlarm1EvalPeriod:
    Description: 'The number of periods over which data is compared to the specified threshold'
    Type: Number
    Default: 1
  pDlqCntAlarm2Thrshld:
    Description: 'Timeframe that a message can remain in the Parser Queue before an e-mail notification is sent indicating a buildup of messages in the queue'
    Type: Number
    Default: 20
  pDlqCntAlarm2Period:
    Description: 'The period, in seconds, over which the statistic is applied'
    Type: Number
    Default: 300
  pDlqCntAlarm2EvalPeriod:
    Description: 'The number of periods over which data is compared to the specified threshold'
    Type: Number
    Default: 1
  pDlqCntAlarm3Thrshld:
    Description: 'Timeframe that a message can remain in the Parser Queue before an e-mail notification is sent indicating a buildup of messages in the queue'
    Type: Number
    Default: 50
  pDlqCntAlarm3Period:
    Description: 'The period, in seconds, over which the statistic is applied'
    Type: Number
    Default: 300
  pDlqCntAlarm3EvalPeriod:
    Description: 'The number of periods over which data is compared to the specified threshold'
    Type: Number
    Default: 1
  pDlqCntAlarm4Thrshld:
    Description: 'Timeframe that a message can remain in the Parser Queue before an e-mail notification is sent indicating a buildup of messages in the queue'
    Type: Number
    Default: 100
  pDlqCntAlarm4Period:
    Description: 'The period, in seconds, over which the statistic is applied'
    Type: Number
    Default: 300
  pDlqCntAlarm4EvalPeriod:
    Description: 'The number of periods over which data is compared to the specified threshold'
    Type: Number
    Default: 1
  pServicenowDomainName:
    Type: "String"
    Default: "/DXC/ServiceNow/DomainName"
    Description: "Domain Name"
  pServicenowBusinessService:
    Type: "String"
    Default: "/DXC/ServiceNow/BusinessService"
    Description: "Business Service name"
  pServicenowCustomerName:
    Type: "String"
    Default: "/DXC/Main/CustomerName"
    Description: "Customer name"
  pServicenowAWSAccountName:
    Type: "String"
    Default: "/DXC/ServiceNow/AWSAccountName"
    Description: "AWS Account Name used for feature Common Servicenow Configuration"

Version: '9.0.0.5'
StandardCreationBatch: 1
EnableFeature: true
Standards:
  - Gold
Owner:
  Name: AWS Platform Engineering Team
  Email: awspe-all@dxc.com
  OtherContactInfo: AWS Platform Engineering team, DXC Technology
Purpose: Allow multiple Lambdas to send data to a single topic which creates an incident in ServiceNow with the desired priority
AllowDisable: true
ResourceDeployment:
  - common_servicenow.yaml
