---
# Feature Definition (FD) for the ConfigRuleLambdaPublicAccessProhibited
# This is a feature that creates Config rule to prohibit Lambda public access

# Partition Key = Feature
# No sort key needed

Feature: ConfigRuleLambdaPublicAccessProhibited
Version: '7.0.0.1'
StandardCreationBatch: 2
EnableFeature: true
Standards:
  - Gold
Owner:
  Name: AWS Platform Engineering Team
  Email: awspe-all@dxc.com
  OtherContactInfo: AWS Platform Engineering team, DXC Technology
Purpose: AWS Config rule to prohibit Lambda public access
AllowDisable: true
ResourceDeployment:
  - LambdaPublicAccessProhibited.yaml
DependsOnFeature:
  - ConfigService