---
# Feature Definition (FD) for AWSLookoutForEquipmentMonitoring

# Partition Key = Feature
# No sort key needed

Feature: AWSLookoutForEquipmentMonitoring
Version: '9.0.0.2'
StandardCreationBatch: 3
EnableFeature: false
Standards:
  - Gold
Owner: 
  Name: AWS Platform Engineering Team
  Email: awspe-all@dxc.com
  OtherContactInfo: AWS Platform Engineering team, DXC Technology
Purpose: Creating the cloudwatch alarms for Lookout For Equipment service in us-east-1, ap-northeast-2, eu-west-1 regions, as currently, it supports these regions.
FeatureParams:
  pCommonIncidentTopic:
    Description: SSM Param to create the Incidents in Service-Now with priroity fetched from DDB - FtCloudWatchAlarmsIncidentPriorities
    Type: "AWS::SSM::Parameter::Value<String>" 
    Default: /DXC/Alarms/CreateIncident-Default
  pSupportedRegions:
    Description: Regions that supports Lookout For Equipment service, use comma seperation.
    Type: String
    Default: "us-east-1,ap-northeast-2,eu-west-1"
  pAutoUpdateHash:
    Description: '[Do Not change] Required to Create/Update the Feature automatically on ses-standards-master update'
    Default: '0'
    Type: String
Alarms:
  InferenceFailed_Alarm:
    ComparisonOperator: GreaterThanThreshold
    Dimensions:
    - Name: Model
      Value: <TO BE FILLED>
    - Name: InferenceScheduler
      Value: <TO BE FILLED>
    EvaluationPeriods: 1
    MetricName: InferenceFailed
    Namespace: AWS/LookoutEquipment
    Period: 300
    Statistic: Maximum
    Threshold: 0

  InferenceInvalidInput_Alarm:
    ComparisonOperator: GreaterThanThreshold
    Dimensions:
    - Name: Model
      Value: <TO BE FILLED>
    - Name: InferenceScheduler
      Value: <TO BE FILLED>
    EvaluationPeriods: 1
    MetricName: InferenceInvalidInput
    Namespace: AWS/LookoutEquipment
    Period: 300
    Statistic: Maximum
    Threshold: 10

ResourceDeployment:
  - aws_lookout_for_equipment_monitoring.yaml
DepensOnFeature:
  - AWSCloudWatchAlarmsIncidentPriorities