---
AWSTemplateFormatVersion: 2010-09-09
Description: "Checks that Amazon S3 buckets do not allow public read access.
  If an Amazon S3 bucket policy or bucket ACL allows public read access,
  the bucket is noncompliant."
Parameters:
  pDXCS3KeyPrefix:
    Type: String
    Default: None
    Description: "[DO NOT CHANGE] S3 path to the Lambda_functions of Feature. To be Filled by creating/parent stack"
  pFeatureVersion:
    Type: String
    Default: 'None'
    Description: "[DO NOT CHANGE] Version of the Feature. To be Filled by creating/parent stack"  
  pwhitelistResources:
    Type: String
    Default: ""
    Description: "S3 bucket names for which no incidents to be created in ServiceNow. seperated by comma, eg:demo1,demo2"  
Resources:
  rAWSConfigRule:
    Type: 'AWS::Config::ConfigRule'
    Properties:
      Description: "Checks that Amazon S3 buckets do not allow public
        read access.  If an Amazon S3 bucket policy or bucket ACL allows
        public read access, the bucket is noncompliant."
      Scope:
        ComplianceResourceTypes:
          - 'AWS::S3::Bucket'
      Source:
        Owner: AWS
        SourceIdentifier: S3_BUCKET_PUBLIC_READ_PROHIBITED
  rWhitelistParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/DXC/ConfigRuleS3PublicRead/Whitelist"
      Type: "String"
      Description: "SSM parameter for storing s3 bucket name for which incidents should not be created in ServiceNow. seperated by comma, eg:demo1,demo2"
      Value: !Ref pwhitelistResources