---
# Feature Definition (FD) for the ConfigRuleEc2Instance
# This is a feature that creates AWS Config rule which checks (by default)
#  whether completed volumes have the following tags
# "Name, Environment, Owner, Project, Compliance"

# Partition Key = Feature
# No sort key needed

Feature: ConfigRuleEbsVolume
Version: '11.0.0.3'
StandardCreationBatch: 2
EnableFeature: true
FeatureParams:
  pFtEbsVolVolumeIdListToSkip:
    Type: String
    Default: "Blank"
    Description: "List of ebs_volumes to be skipped from config compliance check. For multiple volumes to be skipped evaluating against the config rule, use comma separated values."
Standards:
  - Gold
Owner:
  Name: AWS Platform Engineering Team
  Email: awspe-all@dxc.com
  OtherContactInfo: AWS Platform Engineering team, DXC Technology
Purpose: AWS Config rule to verify whether completed volumes have mentioned tags
ScopeOverridesAllowed:
  - Global
  - Customer
  - OrganizationUnit
  - Account
  - Region
  - VPC
  - Subnet
  - Instance
  - Volume
AllowDisable: true
ResourceDeployment:
  - EbsVolumeConfig.yaml
DependsOnFeature:
  - ConfigService