---
# Feature Definition (FD) for AWSQuickSightMonitoring

# Partition Key = Feature
# No sort key needed

Feature: AWSQuickSightMonitoring
Version: '9.0.0.3'
StandardCreationBatch: 3
EnableFeature: false
Standards:
  - Gold
Owner: 
  Name: AWS Platform Engineering Team
  Email: awspe-all@dxc.com
  OtherContactInfo: AWS Platform Engineering team, DXC Technology
Purpose: Creating the cloudwatch alarms for QuickSight service
FeatureParams:
  pCommonIncidentTopic:
    Description: SSM Param to create the Incidents in Service-Now with priroity fetched from DDB - FtCloudWatchAlarmsIncidentPriorities
    Type: "AWS::SSM::Parameter::Value<String>" 
    Default: /DXC/Alarms/CreateIncident-Default
  pAutoUpdateHash:
    Description: '[Do Not change] Required to Create/Update the Feature automatically on ses-standards-master update'
    Default: '0'
    Type: String
Alarms:
  VisualLoadTime_Alarm_1:
    ComparisonOperator: GreaterThanThreshold
    Dimensions:
    - Name: DashboardId
      Value: <To be Filled>
    - Name: SheetId
      Value: <To be Filled>
    - Name: VisualId
      Value: <To be Filled>    
    EvaluationPeriods: 3
    MetricName: VisualLoadTime
    Namespace: AWS/QuickSight
    Period: 300
    Statistic: Average
    Threshold: 30000
  VisualLoadErrorCount_Alarm_1:
    ComparisonOperator: GreaterThanThreshold
    Dimensions:
    - Name: DashboardId
      Value: <To be Filled>
    - Name: SheetId
      Value: <To be Filled>
    - Name: VisualId
      Value: <To be Filled>    
    EvaluationPeriods: 3
    MetricName: VisualLoadErrorCount
    Namespace: AWS/QuickSight
    Period: 300
    Statistic: Average
    Threshold: 10
AllowDisable: true
ResourceDeployment:
  - aws_quicksight_monitoring.yaml
DepensOnFeature:
  - AWSCloudWatchAlarmsIncidentPriorities
