---
# Feature Definition (FD) for the ConfigRuleFullAccessPolicy
# This is a feature that creates AWS Config rule which checks (by default)
# if there are any IAM Roles which are attached with Full Access Policy"

# Partition Key = Feature
# No sort key needed

Feature: ConfigRuleFullAccessPolicy
Version: '9.0.0.2'
StandardCreationBatch: 2
EnableFeature: true
Standards:
  - Gold
Owner:
  Name: AWS Platform Engineering Team
  Email: awspe-all@dxc.com
  OtherContactInfo: AWS Platform Engineering team, DXC Technology
Purpose: AWS Config rule to verify whether Full Access Policies are attached

FeatureParams:
  pfRiskyPolicies:
    Description: 'The risky policies that we are looking for'
    Type: String
    Default: "AmazonEC2FullAccess,AmazonSSMFullAccess,AmazonS3FullAccess"

AllowDisable: true
ResourceDeployment:
  - FullAccessPolicyConfig.yaml
DependsOnFeature:
  - ConfigService
