---
# Feature Definition (FD) for NativebackupEc2LinuxLevel2

# Partition Key = Feature
# No sort key needed

Feature: NativebackupEc2LinuxLevel2
Version: '11.0.0.3'
StandardCreationBatch: 2
EnableFeature: true
Standards:
  - Gold
Owner: 
  Name: AWS Platform Engineering Team
  Email: awspe-all@dxc.com
  OtherContactInfo: AWS Platform Engineering team, DXC Technology
Purpose: AWS Tag based Native backup solution for Ec2 Linux instances

FeatureParams:

  pfCreateNewBackupVault:
    Type: String
    AllowedValues:
      - "true"
      - "false"
    Default: "true"
    Description: "Create new Backup Vault for Ec2 Backup."

  pfBackupVaultName:
    Type: String
    Description: "Enter the Backup Vault Name to be create for Ec2"
    Default: 'Ec2LinuxLevel2BackUpVault'

  pfEc2BackupScheduleExpression:
    Type: String
    Default: "cron(15 12 * * ? *)"
    Description: "AWS Backup cron expression."

  pfBackupDeleteAfterDays:
    Type: Number
    Default: 30
    Description: "Days to expire backups from vault."

  pfBackupConditionTagKey:
    Type: String
    Default: "LinuxNativeBackupLevel"
    Description: "Tag:Key associated with the resources to back up."

  pfBackupConditionTagValue:
    Type: String
    Default: "2"
    Description: "Tag:Value associated with the resources to back up."

  pfVaultMinRetentionDays:
    Type: String
    Default: 30
    Description: "Retention period in days that the vault retains backup data and it should be lesser than or equals to pfBackupDeleteAfterDays."
  
  pSnsTopicName:
    Type: "AWS::SSM::Parameter::Value<String>"
    Default: /DXC/Backups/NativeBackupSnsTopic
    Description: Sns topic name for the failed job notifications.

  # pfVaultMaxRetentionDays:
  #   Type: String
  #   #Default: 30
  #   Default: "dummy"
  #   Description: "The maximum retention period that the vault retains its recovery points.
  #                 Note: Leave it default if you don't need this"

  # pfVaultChangeableForDays:
  #   Type: String
  #   Default: "dummy"
  #   Description: "[WARNING] Number of days before the vault lock. After this period, Vault Lock becomes immutable and cannot be changed or deleted.
  #                 NOTE: If this value is mentioned then, LockConfiguration will be Compliance mode otherwise Governance mode.
  #                 Should be minimum 3 or greater"
  

AllowDisable: true
ResourceDeployment:
  - NativebackupEc2LinuxLevel2.yaml

