AWSTemplateFormatVersion: "2010-09-09"
Description: " This feature creates and registers RHEL Patch Baselines used by RHEL hardening and RHEL Simple Workloads"
# Notes: 
#        The PatchGroups value minus "-patch-group" (rhel8.4, rhel8.2, rhel9.0, etc) must match exactly the versions in QSCreateRhelAMI.json 
#        Until it is confirmed that all customers have stopped using older patch baselines, they cannot be deleted.
#          Thus, no parameters used. For updates, duplicate existing baseline resoure and update with new versions as required, then update QSCreateRhelAMI.json
#        No lambdas are used, so no SSM parameters used.

# 3 required SES parameters
Parameters:
  pDXCS3BucketName:
    Type: "AWS::SSM::Parameter::Value<String>" 
    Default: "/DXC/SES/Module/CreatePatchBaselines/S3AssetBucket"
    Description: "SSM Parameter for bucket location"
  pFeatureVersion:
    Type: String
    Default: 'None'
    Description: "[DO NOT CHANGE] Version of the Feature. To be Filled by creating/parent stack"
  pDXCS3KeyPrefix:
    Type: String
    Default: 'None'
    Description: "[DO NOT CHANGE] S3 path to the Lambda_functions of Feature. To be Filled by creating/parent stack"

Resources:
  rCreateRhel82PatchBaseline:
    Type: AWS::SSM::PatchBaseline
    Properties:
      Name: "dxcms-rhel8.2-patch-baseline"
      Description: "Rhel8.2 Patch Baseline"
      OperatingSystem: "REDHAT_ENTERPRISE_LINUX"
      PatchGroups: 
      - "dxcms-rhel8.2-patch-group"
      ApprovalRules: 
        PatchRules:
        - PatchFilterGroup:
            PatchFilters: 
             - Key: "PRODUCT"
               Values:
                 - RedhatEnterpriseLinux8.2 
             - Key: "CLASSIFICATION"
               Values:
                 - Security 
                 - Bugfix 
             - Key: "SEVERITY"
               Values:
                 - Critical 
                 - Important 
          ApproveAfterDays: 7
      Tags: 
        - Key: "Owner"
          Value: "DXC"

  rCreateRhel84PatchBaseline:
    Type: AWS::SSM::PatchBaseline
    Properties:
      Name: "dxcms-rhel8.4-patch-baseline"
      Description: "Rhel8.4 Patch Baseline"
      OperatingSystem: "REDHAT_ENTERPRISE_LINUX"
      PatchGroups: 
      - "dxcms-rhel8.4-patch-group"
      ApprovalRules: 
        PatchRules:
        - PatchFilterGroup:
            PatchFilters: 
             - Key: "PRODUCT"
               Values:
                 - RedhatEnterpriseLinux8.4 
             - Key: "CLASSIFICATION"
               Values:
                 - Security 
                 - Bugfix 
             - Key: "SEVERITY"
               Values:
                 - Critical 
                 - Important 
          ApproveAfterDays: 7
      Tags: 
        - Key: "Owner"
          Value: "DXC"

  rCreateRhel90PatchBaseline:
    Type: AWS::SSM::PatchBaseline
    Properties:
      Name: "dxcms-rhel9.0-patch-baseline"
      Description: "Rhel9.0 Patch Baseline"
      OperatingSystem: "REDHAT_ENTERPRISE_LINUX"
      PatchGroups: 
      - "dxcms-rhel9.0-patch-group"
      ApprovalRules: 
        PatchRules:
        - PatchFilterGroup:
            PatchFilters: 
             - Key: "PRODUCT"
               Values:
                 - RedhatEnterpriseLinux9.0 
             - Key: "CLASSIFICATION"
               Values:
                 - Security 
                 - Bugfix 
             - Key: "SEVERITY"
               Values:
                 - Critical 
                 - Important 
          ApproveAfterDays: 7
      Tags: 
        - Key: "Owner"
          Value: "DXC"
