---
# Feature Definition (FD) for the WAF as a feature 

# Partition Key = Feature
# No sort key needed

Feature: AwsWaf
Version: '11.0.0.4'
StandardCreationBatch: 3
EnableFeature: False
FeatureParams:
  WebACLName:
    Type: String
    Default: "DxcmsWafWebAcl"
    Description: Provide a name to your WebACL. 
  ALBArn:
    Description: ARN for the Application Load Balancer
    Type: String
    Default: ''
  CwNamePrefix:
    Description: The prefix for use in Name tag values
    Type: String
    MinLength: '5'
    MaxLength: '25'
    Default: cwlogger
  IncludeCommonRuleSet:
    Type: String
    Default: "true"
    AllowedValues:
      - "true"
      - "false"
    Description: Contains common rules (Admin protection (block external access to exposed admin pages), Amazon IP reputation list (based on Amazon threat intelligence), Anonymous IP list (allow you to block requests from services that allow obfuscation of viewer identity.), Core rule set (protection against exploitation of a wide range of vulnerabilities), Known bad inputs (allow you to block request patterns that are known to be invalid and are associated with exploitation or discovery of vulnerabilities)).
  IncludeAdminProtection:
    Type: String
    Default: "true"
    AllowedValues:
      - "true"
      - "false"
    Description: Contains rules that allow you to block external access to exposed admin pages.
  IncludeKnownBadInputs:
    Type: String
    Default: "true"
    AllowedValues:
      - "true"
      - "false"
    Description: Contains rules that allow you to block request patterns that are known to be invalid and are associated with exploitation or discovery of vulnerabilities.  
  IncludeAmazonIPReputationList:
    Type: String
    Default: "true"
    AllowedValues:
      - "true"
      - "false"
    Description: This group contains rules that are based on Amazon threat intelligence. 
  IncludeAnonymousIPList:
    Type: String
    Default: "true"
    AllowedValues:
      - "true"
      - "false"
    Description: This group contains rules that allow you to block requests from services that allow obfuscation of viewer identity. This can include request originating from VPN, proxies, Tor nodes, and hosting providers.
  IncludeLinuxOperatingSystem:
    Type: String
    Default: "true"
    AllowedValues:
      - "true"
      - "false"
    Description: Contains rules that block request patterns associated with exploitation of vulnerabilities specific to Linux, including LFI attacks. This can help prevent attacks that expose file contents or execute code for which the attacker should not have had access.  
  IncludePHPApplication:
    Type: String
    Default: "true"
    AllowedValues:
      - "true"
      - "false"
    Description: Contains rules that block request patterns associated with exploiting vulnerabilities specific to the use of the PHP, including injection of unsafe PHP functions.  
  IncludePOSIXOperatingSystem:
    Type: String
    Default: "true"
    AllowedValues:
      - "true"
      - "false"
    Description: Contains rules that block request patterns associated with exploiting vulnerabilities specific to POSIX/POSIX-like OS, including LFI attacks.  
  IncludeSQLDatabase:
    Type: String
    Default: "true"
    AllowedValues:
      - "true"
      - "false"
    Description: Contains rules that allow you to block request patterns associated with exploitation of SQL databases, like SQL injection attacks. This can help prevent remote injection of unauthorized queries.  
  IncludeWindowsOperatingSystem:
    Type: String
    Default: "true"
    AllowedValues:
      - "true"
      - "false"
    Description: Contains rules that block request patterns associated with exploiting vulnerabilities specific to Windows, (e.g., PowerShell commands). This can help prevent exploits that allow attacker to run unauthorized commands or execute malicious code.  
  IncludeWordpressApplication:
    Type: String
    Default: "true"
    AllowedValues:
      - "true"
      - "false"
    Description: The WordPress Applications group contains rules that block request patterns associated with the exploitation of vulnerabilities specific to WordPress sites.  
  # IncludeAccountCreationFraudPrevention:
  #   Type: String
  #   Default: "false"
  #   AllowedValues:
  #     - "true"
  #     - "false"
  #   Description: Provides protection against the creation of fraudulent accounts on your site. Fraudulent accounts can be used for activities such as obtaining sign-up bonuses and impersonating legitimate users.  
  # IncludeAccountTakeoverPrevention:
  #   Type: String
  #   Default: "false"
  #   AllowedValues:
  #     - "true"
  #     - "false"
  #   Description: Provides protection for your login page against stolen credentials, credential stuffing attacks, brute force login attempts, and other anomalous login activities. With account takeover prevention, you can prevent unauthorized access that may lead to fraudulent activities, or inform legitimate users to take a preventive action.

  PriorityIncidentTopic:
    Description: SSM Param to create the Incidents in Service-Now with priority fetched from DDB - FtCloudWatchAlarmsIncidentPriorities
    Type: "AWS::SSM::Parameter::Value<String>" 
    Default: /DXC/Alarms/CreateIncident-Default

  WAFBlockedRequestAlarm:
    Description: 'Enable for creating WAF Blocked Requests Alarm. Pre-Requisite FeatureAWSCloudWatchAlarmsIncidentPriorities is deployed.'
    Type: String
    AllowedValues: ['true', 'false']
    Default: 'true'
  WAFBlockedRequestPeriod:
    Description: 'The period, in seconds, over which the statistic is applied. This is required for an alarm based on a metric. Valid values are 10, 30, 60, and any multiple of 60.'
    Type: Number
    Default: 60
  WAFBlockedRequestStatistic:
    Description: 'The statistic for the metric associated with the alarm'
    Type: String
    AllowedValues: ['Average','Maximum', 'Minimum', 'SampleCount', 'Sum']
    Default: 'Sum'
  WAFBlockedRequestThreshold:
    Description: 'The value to compare with the specified statistic.'
    Type: Number
    Default: 1

  WAFBlockedRequestEvaluationPeriods:
    Description: 'The number of periods over which data is compared to the specified threshold.'
    Type: Number
    Default: 2
  WAFBlockedRequestComparisonOperator:
    Description: 'The arithmetic operation to use when comparing the specified statistic and threshold. The specified statistic value is used as the first operand.'
    Type: String
    Default: 'GreaterThanOrEqualToThreshold'
    AllowedValues: ['GreaterThanOrEqualToThreshold','GreaterThanThreshold','GreaterThanUpperThreshold','LessThanLowerOrGreaterThanUpperThreshold','LessThanLowerThreshold','LessThanOrEqualToThreshold', 'LessThanThreshold']
  
  S3BucketNameForWafRulesBackup:
    Type: String
    Default: ""
    Description: Provide S3 Bucket Name for storing rules and configuration of WAF WebACL on daily basis.
Standards:
  - Gold
Owner:
  Name: AWS Platform Engineering Team
  Email: awspe-all@dxc.com
  OtherContactInfo: AWS Platform Engineering team, DXC Technology
Purpose: Creating a WAF WebACL and configuring it with some AWS Managed Rules to protect websites & web application from web exploits or malicious attacks.
AllowDisable: true
ResourceDeployment:
  - AwsWaf.yaml
DependsOnFeature:
  - AWSCloudWatchAlarmsIncidentPriorities