---
# Feature Definition (FD) for AWSCloudFrontMonitoring

# Partition Key = Feature
# No sort key needed

Feature: AWSCloudFrontMonitoring
Version: '9.0.0.3'
StandardCreationBatch: 3
EnableFeature: false
Standards:
  - Gold
Owner: 
  Name: AWS Platform Engineering Team
  Email: awspe-all@dxc.com
  OtherContactInfo: AWS Platform Engineering team, DXC Technology
Purpose: Creating the cloudwatch alarms for CloudFront service in us-east-1 region, as CloudFront is Global service
FeatureParams:
  pCommonIncidentTopic:
    Description: SSM Param to create the Incidents in Service-Now with priroity fetched from DDB - FtCloudWatchAlarmsIncidentPriorities
    Type: "AWS::SSM::Parameter::Value<String>" 
    Default: /DXC/Alarms/CreateIncident-Default
  pAutoUpdateHash:
    Description: '[Do Not change] Required to Create/Update the Feature automatically on ses-standards-master update'
    Default: '0'
    Type: String
Alarms:
  4xxErrorRate_AmplifyHost_Alarm:
    ComparisonOperator: GreaterThanThreshold
    Dimensions:
    - Name: App
      Value: <To be Filled>
    EvaluationPeriods: 3
    MetricName: 4xxErrors
    Namespace: AWS/AmplifyHosting
    Period: 300
    Statistic: Sum
    Threshold: 5
  5xxErrorRate_AmplifyHost_Alarm:
    ComparisonOperator: GreaterThanThreshold
    Dimensions:
    - Name: App
      Value: <To be Filled>     
    EvaluationPeriods: 3
    MetricName: 5xxErrors
    Namespace: AWS/AmplifyHosting
    Period: 300
    Statistic: Sum
    Threshold: 5
  4xxErrorRate_Alarm:
    ComparisonOperator: GreaterThanThreshold
    Dimensions:
    - Name: DistributionId
      Value: <To be Filled>
    - Name: Region
      Value: Global       
    EvaluationPeriods: 3
    MetricName: 4xxErrorRate
    Namespace: AWS/CloudFront
    Period: 300
    Statistic: Sum
    Threshold: 5
  5xxErrorRate_Alarm:
    ComparisonOperator: GreaterThanThreshold
    Dimensions:
    - Name: DistributionId
      Value: <To be Filled>
    - Name: Region
      Value: Global       
    EvaluationPeriods: 3
    MetricName: 5xxErrorRate
    Namespace: AWS/CloudFront
    Period: 300
    Statistic: Sum
    Threshold: 5
AllowDisable: true
ResourceDeployment:
  - aws_cloud_front_monitoring.yaml
DepensOnFeature:
  - AWSCloudWatchAlarmsIncidentPriorities