---
# Feature Definition (FD) for EksEc2BasedCluster

# Partition Key = Feature
# No sort key needed

Feature: EksEc2BasedCluster 
Version: '9.0.0.2'
StandardCreationBatch: 3
EnableFeature: false
Standards:
  - Gold
Owner: 
  Name: AWS Platform Engineering Team
  Email: awspe-all@dxc.com
  OtherContactInfo: AWS Platform Engineering team, DXC Technology
Purpose: Creation of EKS Cluster along with nodegroup, launch template

EKSEc2BasedClusterParameters:

  ClusterName:
    Description: Name of the EKS cluster
    Type: String
    Default: 'EKSCluster-1'

  EKSClusterVersion:
    Description: Version of the EKS cluster. Leave it empty for default version 
    Type: String
    Default: ""

  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: The VPC of the worker instances
    Default: "<vpc-12345>"

  Subnets:
    Type: String
    Default: "dummy"
    Description: The subnets where workers can be created. Leave Default as 'dummy' if you want to pull the private subnets
                  automatically. Otherwise, give the subnets as comma separated values ex- 'subnet-abcd1,subnetabcd2'

  SnowInciPriority:
    Description: '[Required] Default is set to 3-Minor, other priorities are 1-critical, 2-major, 3-minor, 4-warning, 5-ok (can be updated if necessary)'
    Type: String
    Default: '3'
    AllowedValues: ['1', '2', '3', '4', '5']
    
AllowDisable: true
ResourceDeployment:
  - EksEc2BasedCluster.yaml
DepensOnFeature:
  - CommonServicenow  

